stages:
  - test
  - build
  - deploy
  - clean

variables:
  TAG: py3-template
  CONTAINER_NAME: py3-template-serivce
  # TARGET_REGISTRY: container_registry

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-image:
  stage: build
  script:
    - docker build -t $TAG .
    # - docker push $TARGET_REGISTRY

  only:
    refs:
      - develop
    changes:
      - Dockerfile
      - main.py

  tags:
    - dev-ci-runner

dev-deploy:
  stage: deploy
  script:
    - docker pull $TAG
    - docker container inspect $CONTAINER_NAME && docker rm -f $CONTAINER_NAME
    - docker-compose -f ./deploy/dev-docker-compose.yml up -d --no-build

  only:
    refs:
      - develop
    changes:
      - Dockerfile
      - main.py

  tags:
    - dev-ci-runner

release-deploy:
  stage: deploy
  script:
    - docker pull $TAG
    - docker container inspect $CONTAINER_NAME && docker rm -f $CONTAINER_NAME
    - docker-compose -f ./deploy/dev-docker-compose.yml up -d --no-build

  only:
    refs:
      - master
    changes:
      - Dockerfile
      - main.py

  tags:
    - release-ci-runner